kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: resizable-pvc
  annotations:
    resize.topolvm.io/storage_limit: 10Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 2Gi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app.kubernetes.io/name: example-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command:
      - bash
      - -c
      - |
        sleep inf &
        trap "kill -SIGTERM $!" SIGTERM
        wait $!
        exit
    volumeMounts:
    - mountPath: /test1
      name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: resizable-pvc
