name: "e2e"
on:
  pull_request:
    paths-ignore:
        - "**/*.md"
        - "CODEOWNERS"
  push:
    paths-ignore:
        - "**/*.md"
        - "CODEOWNERS"
    branches:
      - "main"
jobs:
  e2e-k8s:
    name: "e2e-k8s"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        kubernetes_versions: ["1.30.0", "1.29.4", "1.28.9"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make -C test/e2e setup
      - run: make -C test/e2e init-app-with-cert-manager
      - run: make -C test/e2e test

  e2e-k8s-without-cert-manager:
    name: "e2e-k8s-without-cert-manager"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        kubernetes_versions: ["1.30.0", "1.29.4", "1.28.9"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make -C test/e2e setup
      - run: make -C test/e2e init-app-without-cert-manager
      - run: make -C test/e2e test

  e2e-k8s-with-metrics-api:
    name: "e2e-k8s-with-metrics-api"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        kubernetes_versions: ["1.30.0", "1.29.4", "1.28.9"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make -C test/e2e setup
      - run: make -C test/e2e init-app-with-metrics-api
      - run: make -C test/e2e test
