name: "Release Charts"

on: "workflow_dispatch"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Add depending repository for helm to avoid the error below.
      # `Error: no repository definition for https://charts.jetstack.io`
      # see: https://github.com/helm/chart-releaser-action/issues/74
      - name: "Add cert-manager repo for helm"
        run: |
          helm repo add cert-manager https://charts.jetstack.io

      - name: Login to Helm registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/appian --username ${{ github.actor }} --password-stdin
      - name: Package chart
        run: helm package --dependency-update ./charts/pvc-autoresizer
      - name: Publish chart
        run: |
          chartVersion=$(helm show chart ./charts/pvc-autoresizer | grep -E "^version:" | awk '{print $2}')
          helm push ./pvc-autoresizer-${chartVersion}.tgz oci://ghcr.io/appian/charts
